In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import quandl

import pickle

from matplotlib import style
style.use('ggplot')

In [9]:
HPI_data = pd.read_pickle('data/new_file3.pickle')
HPI_data.head()

,ValueAK,ValueAZ,ValueAR,ValueCA,ValueCO,ValueCT,ValueDE,ValueFL,ValueGA,ValueHI,...,ValueTN,ValueTX,ValueUT,ValueVT,ValueVA,ValueWA,ValueWV,ValueWI,ValueWY,Value
Date,,,,,,,,,,,,,,,,,,,,,
1975-01-31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1975-02-28,0.626500,1.485775,1.688504,0.846192,0.356177,1.159639,2.123926,0.142451,3.938796,-0.902841,...,-1.099859,0.112132,0.951488,1.398290,0.945247,0.987288,0.397561,2.495069,1.404920,1.438502
1975-03-31,1.358575,3.006473,3.261346,1.581956,1.575690,2.299449,3.719898,0.387918,9.798243,-1.282758,...,-2.218400,0.369186,2.701039,2.659262,1.857227,1.707474,1.015723,5.093474,2.791371,2.962512
1975-04-30,2.254726,4.593530,4.475810,2.183669,3.573196,3.359028,4.616778,0.891619,16.974819,-1.068371,...,-3.328868,0.765570,5.276570,3.662119,2.685578,2.238392,1.757887,7.772685,4.034165,4.545011
1975-05-31,3.107829,6.327600,5.139617,2.786248,5.241395,4.226895,4.901787,1.752086,17.891884,-0.676830,...,-4.335377,1.228808,6.099286,4.326186,3.413295,2.684036,2.426439,10.469784,5.047628,6.080901

In [27]:
plt.figure()
ax1 = plt.subplot2grid((1,1),(0,0))

#resample
"""
Alias	Description
B	business day frequency
C	custom business day frequency (experimental)
D	calendar day frequency
W	weekly frequency
M	month end frequency
BM	business month end frequency
CBM	custom business month end frequency
MS	month start frequency
BMS	business month start frequency
CBMS	custom business month start frequency
Q	quarter end frequency
BQ	business quarter endfrequency
QS	quarter start frequency
BQS	business quarter start frequency
A	year end frequency
BA	business year end frequency
AS	year start frequency
BAS	business year start frequency
BH	business hour frequency
H	hourly frequency
T	minutely frequency
S	secondly frequency
L	milliseonds
U	microseconds
N	nanoseconds
"""
CA1yr = HPI_data['ValueCA'].resample('A',how = 'mean')
print CA1yr.head()

HPI_data['ValueCA'].plot(ax=ax1,color = 'b',label = 'default: monthly')
CA1yr.plot(ax = ax1,color = 'g',label = 'resampled: yearly')

plt.legend(loc = 'upper left')
plt.show()

C:\Users\phay\Anaconda2\lib\site-packages\ipykernel\__main__.py:33: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).mean()

Date
1975-12-31     3.119870
1976-12-31    10.692791
1977-12-31    19.540484
1978-12-31    31.039674
1979-12-31    46.726417
Freq: A-DEC, Name: ValueCA, dtype: float64

In [30]:
plt.figure()
ax1 = plt.subplot2grid((1,1),(0,0))

CA1yr = HPI_data['ValueCA'].resample('A',how = 'ohlc')
print CA1yr.head()

HPI_data['ValueCA'].plot(ax=ax1,color = 'b',label = 'default: monthly')
CA1yr.plot(ax = ax1,label = 'resampled: ohlc')

plt.legend(loc = 'upper left')
plt.show()

C:\Users\phay\Anaconda2\lib\site-packages\ipykernel\__main__.py:4: FutureWarning: how in .resample() is deprecated
the new syntax is .resample(...).ohlc()

                 open       high        low      close
Date
1975-12-31   0.000000   4.917757   0.000000   4.917757
1976-12-31   5.559395  14.101041   5.559395  14.101041
1977-12-31  14.763413  23.700049  14.763413  23.700049
1978-12-31  24.456591  37.484905  24.456591  37.484905
1979-12-31  38.595847  53.439005  38.595847  52.948167